version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: utkrusht_admin
      POSTGRES_PASSWORD: tenantpass2024
      POSTGRES_DB: tenant_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://utkrusht_admin:tenantpass2024@db:5432/tenant_db
    ports:
      - '8000:8000'
volumes:
  pgdata:
